# numpy_practice1

편의점 판매 데이터를 NumPy로 다루는 실습이다.

범위:
- 01_ndarray
- 02_indexing_slicing
- 03_operation
- 04_statistics

규칙:
- 각 문제 아래 코드 셀에서 직접 풀이
- 필요한 경우 셀 추가 가능
- 배열의 shape를 함께 확인하는 습관을 가지기

## 0. 시작 데이터

In [1]:
import numpy as np

# 3개 지점의 5일치 음료 판매량
# 행: 지점, 열: 날짜
sales = np.array([
    [12, 15, 14, 10, 13],
    [ 9, 11, 10, 12,  8],
    [14, 13, 16, 15, 17]
])

# 지점별 음료 가격
prices = np.array([1800, 2000, 2200])

sales

array([[12, 15, 14, 10, 13],
       [ 9, 11, 10, 12,  8],
       [14, 13, 16, 15, 17]])

## 1. ndarray 기본 확인
1) sales의 shape, ndim, size, dtype를 확인하시오.
2) prices의 shape를 확인하시오.

In [2]:
# 1. sales
print(sales.shape)
print(sales.ndim)
print(sales.size)
print(sales.dtype)

# 2. prices
print(prices.shape)

(3, 5)
2
15
int64
(3,)


## 2. 배열 생성
1) 길이가 5인 0 배열을 만드시오.
2) 3 x 5 형태의 1 배열을 만드시오.
3) 모든 값이 7인 2 x 3 배열을 만드시오.
4) 0부터 9까지의 값을 가지는 1차원 배열을 만드시오.

In [3]:
arr1 = np.zeros([1, 5],dtype=int)
arr2 = np.ones([3, 5],dtype=int)
arr3 = np.full([2, 3], 7, dtype=int)
arr4 = np.arange(0, 10)

print(f"1: {arr1}")
print(f"2: {arr2}")
print(f"3: {arr3}")
print(f"4: {arr4}")

1: [[0 0 0 0 0]]
2: [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
3: [[7 7 7]
 [7 7 7]]
4: [0 1 2 3 4 5 6 7 8 9]


## 3. 인덱싱
1) 첫 번째 지점의 첫째 날 판매량을 선택하시오.
2) 세 번째 지점의 넷째 날 판매량을 선택하시오.
3) 마지막 지점의 마지막 날 판매량을 음수 인덱스로 선택하시오.

In [4]:
first_index = sales[0, 0]
print(f"첫 번째 지점 첫째 날 판매량: {first_index}")
second_index = sales[2, 3]
print(f"세 번째 지점 넷째 날 판매량: {second_index}")
third_index = sales[-1, -1]
print(f"마지막 지점 마지막 날 판매량(음수 선택): {third_index}")

첫 번째 지점 첫째 날 판매량: 12
세 번째 지점 넷째 날 판매량: 15
마지막 지점 마지막 날 판매량(음수 선택): 17


## 4. 슬라이싱
1) 첫 번째 지점의 전체 판매량을 선택하시오.
2) 모든 지점의 첫 3일 판매량을 선택하시오.
3) 두 번째와 세 번째 지점만 선택하시오.

In [ ]:
first_slicing = sales[1, :]
print(f"첫 번째 지점 전체 판매량: {first_slicing}")
second_slicing = sales[:, :3]
print(f"모든 지점 첫 3일 판매량: {second_slicing}")
third_slicing = sales[1:3, :]
print(f"두 번째 & 세 번째 지점: {third_slicing}")

첫 번째 지점 전체 판매량: [ 9 11 10 12  8]
모든 지점 첫 3일 판매량: [[12 15 14]
 [ 9 11 10]
 [14 13 16]]
두 번째 & 세 번째 지점: [[ 9 11 10 12  8]
 [14 13 16 15 17]]


## 5. Fancy Indexing
첫째 날과 셋째 날 판매량만 모든 지점에서 선택하시오.

In [12]:
arr5 = np.array([0, 2])
first_and_third_sales = sales[arr5, :]
first_and_third_sales

array([[12, 15, 14, 10, 13],
       [14, 13, 16, 15, 17]])

## 6. Boolean Indexing
1) 판매량이 13 이상인 값만 선택하시오.
2) sales에서 10 미만인 값의 개수를 구하시오.

In [52]:
boolean_one = sales >= 13
print(f"1번 \n", sales[boolean_one])

boolean_two = sales < 10
print(f"2번\n", len(sales[boolean_two]))

1번 
 [15 14 13 14 13 16 15 17]
2번
 2


## 7. 기본 연산
1) sales에 2를 더하시오.
2) sales에 2를 곱하시오.
3) sales와 같은 shape의 discount 배열을 만든 뒤 더하시오.
   discount = np.array([[0,1,0,1,0],[1,0,1,0,1],[0,0,1,1,0]])

In [ ]:
print("1번 : sales + 2\n", sales + 2)
print("2번 : sales * 2\n", sales * 2)
discount = np.array([[0,1,0,1,0],[1,0,1,0,1],[0,0,1,1,0]])
print("3번 : sales + discount\n",discount + sales)

1번 : sales + 2
 [[14 17 16 12 15]
 [11 13 12 14 10]
 [16 15 18 17 19]]
2번 : sales * 2
 [[24 30 28 20 26]
 [18 22 20 24 16]
 [28 26 32 30 34]]
3번 : sales + discount
 [[12 16 14 11 13]
 [10 11 11 12  9]
 [14 13 17 16 17]]


## 8. Broadcasting
지점별 가격 prices를 sales에 곱해서 revenue 배열을 만드시오.
힌트: sales는 판매량, prices는 지점별 단가이다.

In [111]:
prices = prices.reshape(3, 1)
revenue = prices * sales
revenue

array([[21600, 27000, 25200, 18000, 23400],
       [18000, 22000, 20000, 24000, 16000],
       [30800, 28600, 35200, 33000, 37400]])

## 9. 수학 함수
revenue 배열에서
1) 전체 합계
2) 지점별 합계
3) 날짜별 합계
를 구하시오.

In [116]:
print(f"1. 전체 합계 : ", np.sum(revenue))
print(f"2. 지점별 합계 : ", np.sum(revenue, axis = 1))
print(f"3. 날짜별 합계 : ", np.sum(revenue, axis = 0))

1. 전체 합계 :  380200
2. 지점별 합계 :  [115200 100000 165000]
3. 날짜별 합계 :  [70400 77600 80400 75000 76800]


## 10. 행렬곱
아래 promo 배열은 날짜별 행사 가중치이다.
sales와 promo를 행렬곱하여 지점별 행사 점수를 구하시오.

In [55]:
promo = np.array([1.0, 0.8, 1.2, 1.1, 0.9])

event_score = sales@promo
print(event_score)

[63.5 50.2 75.4]


## 11. 통계 기본
sales 배열에서
1) 평균
2) 중앙값
3) 최댓값
4) 최솟값
을 구하시오.

In [58]:
print(f"1번 평균 : {np.mean(sales)}")
print(f"2번 중앙값 : {np.median(sales)}")
print(f"3번 최댓값 : {np.max(sales)}")
print(f"4번 최소값 : {np.min(sales)}")

1번 평균 : 12.6
2번 중앙값 : 13.0
3번 최댓값 : 17
4번 최소값 : 8


## 12. 축 기준 통계
1) 지점별 평균 판매량
2) 날짜별 평균 판매량
3) 지점별 표준편차
를 구하시오.

In [64]:
spot_mean = np.mean(sales, axis=1)
print(f"지점별 평균 판매량: {spot_mean}")
day_mean = np.mean(sales, axis = 0)
print(f"날짜별 평균 판매량: {day_mean}")
spot_std = np.std(spot_mean)
print(f"지점별 표준편차: {spot_std}")

지점별 평균 판매량: [12.8 10.  15. ]
날짜별 평균 판매량: [11.66666667 13.         13.33333333 12.33333333 12.66666667]
지점별 표준편차: 2.046134567096374


## 13. 난수와 통계
평균 100, 표준편차 10인 고객 방문 수 데이터를 30개 생성하시오.
그리고 평균과 표준편차를 구하시오.

In [91]:
customer_visit_data = np.random.normal(100, 10, 30)
print(customer_visit_data)
print(f"평균 : {np.mean(customer_visit_data)}, 표준편차 : {np.std(customer_visit_data)}")

[106.12701268 106.06627235  84.84123057  84.90640352  86.58699129
  86.80062943  96.85410389 120.67430728 102.96286788  90.42564972
 114.44937048  87.49564536  95.707875   108.49237605  89.52384612
 103.01719003  85.40110794 117.9666699   94.75893465  98.72077974
  95.83336186 104.5867427   88.56887367  99.77327286 112.79131921
 112.73008651  91.02135635 106.8125953   92.88220633  95.94314953]
평균 : 98.7574076066086, 표준편차 : 10.337701682493737


## 14. 종합 문제
아래 inventory는 지점별 현재 재고이다.
1) 예상 판매량 sales와 비교해 부족한 재고 위치를 True/False로 구하시오.
2) 부족한 위치의 개수를 구하시오.
3) 부족한 위치의 판매량 값만 선택하시오.

In [107]:
inventory = np.array([
    [15, 14, 15, 12, 10],
    [10, 10,  9, 13,  9],
    [13, 13, 15, 14, 16]
])

need_more = inventory<sales
print(f"1. 부족한 재고 위치 \n", need_more)
print(f"2. 부족한 위치의 개수 \n", len(inventory[need_more]) )
print(f"3. 부족한 위치의 판매량 \n", inventory[need_more])

1. 부족한 재고 위치 
 [[False  True False False  True]
 [False  True  True False False]
 [ True False  True  True  True]]
2. 부족한 위치의 개수 
 8
3. 부족한 위치의 판매량 
 [14 10 10  9 13 15 14 16]
